#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7

bspc config focus_follows_pointer true
bspc config pointer_follows_focus true

bspc config border_width        0
bspc config window_gap          8

bspc config focused_border_color "#43b365"
bspc config normal_border_color "#393939"
bspc config left_padding 3
bspc config right_padding 3

bspc config split_ratio 0.6

bspc config automatic_scheme longest_side
bspc config initial_polarity second_child


bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


# Mouse settings
/home/tokyob0t/.config/eww/scripts/MAIN &&
copyq &
picom -f &

# Keyboard settings
setxkbmap latam &
workspaces=(1 2 3 4 5 6 7)

for i in "${workspaces[@]}"; do
    bsp-layout set tall "$i"
done &
