#!/bin/bash

# Obtener la información de la batería usando upower
battery_info=$(upower -i /org/freedesktop/UPower/devices/battery_BAT1)
battery_percentage=$(echo "$battery_info" | grep -E "percentage" | awk '{print $2}' | tr -d '%')
battery_state=$(echo "$battery_info" | grep -E "state" | awk '{print $2}')
choice=$1
# Función para obtener el nivel de batería (percentage) sin el símbolo de porcentaje
get_battery_percentage() {
    echo "$battery_percentage"
}


# Función para obtener el estado de la batería (state)
get_battery_state() {
    echo "$battery_state"
}

battery_animation() {
    mi_array=("󰢟" "󰢜" "󰂆" "󰂇" "󰂈" "󰢝" "󰂉" "󰢞" "󰂊" "󰂋" "󰂅")
    for valor in "${mi_array[@]}"; do
    eww update "battery_charging"="$valor"
    sleep 0.5
    done
}

battery_default(){
    if [ "$battery_state" == "fully-charged" ]; then
        echo "󰂄"
    elif [ "$battery_percentage" -ge 98 ]; then
        echo "󰁹"
    elif [ "$battery_percentage" -ge 90 ]; then
        echo "󰂂"
    elif [ "$battery_percentage" -ge 80 ]; then
        echo "󰂁"
    elif [ "$battery_percentage" -ge 70 ]; then
        echo "󰂀"
    elif [ "$battery_percentage" -ge 60 ]; then
        echo "󰁿"
    elif [ "$battery_percentage" -ge 50 ]; then
        echo "󰁾"
    elif [ "$battery_percentage" -ge 40 ]; then
        echo "󰁽"
    elif [ "$battery_percentage" -ge 30 ]; then
        echo "󰁼"
    elif [ "$battery_percentage" -ge 20 ]; then
        echo "󰁻"
    else
        echo "󰂎"
    fi
}


# Comprobar las banderas de línea de comandos
if [ "$choice" = "--per" ]; then
    get_battery_percentage
elif [ "$choice" = "--state" ]; then
    get_battery_state
elif [ "$choice" = "--anim" ]; then
    battery_animation
elif [ "$choice" = "--icon" ]; then
    battery_default
else
    echo ""
fi
