#!/usr/bin/bash

# Obtener la información de la batería usando upower
battery_info=$(upower -i /org/freedesktop/UPower/devices/battery_BAT1)
battery_percentage=$(echo "$battery_info" | grep -E "percentage" | awk '{print $2}' | tr -d '%')
battery_state=$(echo "$battery_info" | grep -E "state" | awk '{print $2}')
choice=$1

# Función para obtener el nivel de batería (percentage) sin el símbolo de porcentaje
returnjson(){
    echo "{\"num\": \"$battery_percentage\", \"state\": \"$battery_state\", \"icon\": \"$(icon)\"}"
}

icon() {
    case $battery_state in
        "fully-charged")
            echo "󰂄"
            ;;
        *)
            if [ "$battery_percentage" -ge 90 ]; then
                echo "󰁹"
            elif [ "$battery_percentage" -ge 85 ]; then
                echo "󰂂"
            elif [ "$battery_percentage" -ge 70 ]; then
                echo "󰂁"
            elif [ "$battery_percentage" -ge 65 ]; then
                echo "󰂀"
            elif [ "$battery_percentage" -ge 60 ]; then
                echo "󰁿"
            elif [ "$battery_percentage" -ge 55 ]; then
                echo "󰁾"
            elif [ "$battery_percentage" -ge 50 ]; then
                echo "󰁽"
            elif [ "$battery_percentage" -ge 45 ]; then
                echo "󰁼"
            elif [ "$battery_percentage" -ge 40 ]; then
                echo "󰁻"
            else
                echo "󰂎"
            fi
            ;;
    esac
}


checkbattery() {
    case $battery_state in
        "discharging")
            if [ "$battery_percentage" -le 10 ]; then
                notify-send --app-name=Battery "Battery Percentaje 10%" "IMM GONNA SHUTDOWNN SOOON"
            elif [ "$battery_percentage" -le 15 ]; then
                notify-send --app-name=Battery "Battery Percentaje 15%" "CONnEECT THE STUPID PLUG"
            elif [ "$battery_percentage" -le 20 ]; then
                notify-send --app-name=Battery "Battery Percentaje 20%" "Hey stupid, 20% left"
            elif [ "$battery_percentage" -le 30 ]; then
                notify-send --app-name=Battery "Battery Percentaje 30%" "Please connect the charger"
            fi
            ;;
    esac
}


# Comprobar las banderas de línea de comandos
if [ "$choice" = "--json" ]; then
    returnjson
    checkbattery
fi
