#!/bin/bash

new_brightness="$1"

if [ "$new_brightness" -lt 10 ]; then
    new_brightness=10
elif [ "$new_volume" -gt 100 ]; then
    new_volume=100
fi

# Redondear el nuevo volumen al múltiplo de 2 más cercano
new_brightness=$((new_brightness / 3 * 3))

light -S "$new_brightness%"

echo "Brillo Ajustado: $new_brightness%"
