#!/usr/bin/bash

FOCUSED_DESKTOP=$(bspc query -D -d focused --names)
LAYOUT=$(bsp-layout get $FOCUSED_DESKTOP)
json="{\"icon\": \"\", \"layout\": \"$LAYOUT\"}"
layoutjson='{
		"floating": "./img/layouts/floatingw.png",
		"magnifier": "./img/layouts/magnifierw.png",
		"max": "./img/layouts/maxw.png",
		"fullscreen": "./img/layouts/fullscreenw.png",
		"tile": "./img/layouts/tilew.png",
		"tileleft": "./img/layouts/tileleftw.png",
		"tilebottom": "./img/layouts/tilebottomw.png",
		"tiletop": "./img/layouts/tiletopw.png",
		"fairv": "./img/layouts/fairvw.png",
		"fairh": "./img/layouts/fairhw.png",
		"spiral": "./img/layouts/spiralw.png",
		"dwindle": "./img/layouts/dwindlew.png",
		"cornernw": "./img/layouts/cornernww.png"
		}'

case $1 in
	"--icon")
		case $LAYOUT in
			tall)
				echo $layoutjson | jq -r .tile
				;;
			rtall)
				echo $layoutjson | jq -r .tileleft
				;;
			wide)
				echo $layoutjson | jq -r .tilebottom
				;;
			rwide)
				echo $layoutjson | jq -r .tiletop
				;;
			grid)
				echo $layoutjson | jq -r .fairh
				;;
			rgrid)
				echo $layoutjson | jq -r .fairv
				;;
			tiled)
				echo $layoutjson | jq -r .dwindle
				;;
			even)
				echo $layoutjson | jq -r .cornernw
				;;
			monocle)
				echo $layoutjson | jq -r .magnifier
				;;
			*)
				echo "Layout no reconocido: $layout"
				;;
		esac
		;;
	"--set")
		bsp-layout next --layouts rtall,wide,grid,tiled --master-size 40 --desktop $FOCUSED_DESKTOP
		;;
	"--reset")
		bsp-layout set tiled $FOCUSED_DESKTOP
		;;
esac