#!/bin/bash

# Obtener información de workspaces y crear un JSON
get_workspace_info() {
    monitor=""
    [ -n "$1" ] && monitor="--monitor $1"
    
    # Almacenar los resultados de bspc para evitar llamadas innecesarias
    desktops=($(bspc query -D --names $monitor))
    focused_desktop=($(bspc query -D -d focused --names $monitor))
    occupied_desktops=($(bspc query -D -d .occupied --names $monitor))
    
    workspaces=()
    
    for d in "${desktops[@]}"; do
        if [[ " ${focused_desktop[@]} " =~ " $d " ]]; then
            class="active"
        elif [[ " ${occupied_desktops[@]} " =~ " $d " ]]; then
            class="inactive"
        else
            class="empty"
        fi

        workspaces+=("{\"id\":\"$d\",\"state\":\"$class\"}")
    done

    # Generar JSON
    echo "["$(IFS=','; echo "${workspaces[*]}")"]"
}

# Escuchar cambios en bspwm
bspc subscribe desktop node_transfer | while read -r _ ; do
    workspace_info=$(get_workspace_info)
    echo "$workspace_info"
done
