#!/bin/bash

choice="$1"
bluetooth_status=$(rfkill list bluetooth | grep -o "Soft blocked: [a-z]*")

bluetooth_toggle(){
    if [ "$bluetooth_status" == "Soft blocked: no" ]; then
        rfkill block bluetooth
    else
        rfkill unblock bluetooth
    fi
}

bluetooth_color(){
    if [ "$bluetooth_status" == "Soft blocked: no" ]; then
        echo '#6791da'
    else
        echo '#232323'
    fi
}

bluetooth_icon() {
    if [ "$bluetooth_status" == "Soft blocked: no" ]; then
        echo "  󰂯"
    else
        echo "  󰂲"
    fi
}

if [ $choice == "--toggle" ]; then
    bluetooth_toggle
elif [ $choice == "--name" ]; then
    bluetooth_name
elif [ $choice == "--col" ]; then
    bluetooth_color
elif [ $choice == "--icon" ]; then
    bluetooth_icon
fi


