#!/bin/bash

BATTERY="/org/freedesktop/UPower/devices/battery_BAT1"

ICON=("󰁹" "󰂂" "󰂁" "󰂀" "󰁿" "󰁾" "󰁽" "󰁼" "󰁻" "󰁺" "󰂎")
ICON_CHARGING=("󰂅" "󰂋" "󰂊" "󰢞" "󰂉" "󰢝" "󰂈" "󰂇" "󰂆" "󰢜" "󰢟")

declare -A dict
dict=(
	["state"]=""
	["percentage"]=0
	["icon"]=""
	["class"]=""
	["time_to"]="Time to full: 1.5 hours"
)
main() {
	local charging
	while IFS= read -r line; do
		IFS=':' read -r key value <<<"$line"
		key=$(echo "$key" | tr -d ' ')
		value=$(echo "$value" | tr -d ' ')

		case "$key" in
		state)
			dict["state"]=$(echo "$value" | tr '[:upper:]' '[:lower:]')
			;;
		percentage)
			dict["percentage"]=${value%\%}
			charging=$(echo "${dict["state"]}")
			if [ "$charging" == "charging" ] || [ "$charging" == "pending-charge" ]; then
				dict["class"]="charging"
				dict["icon"]=${ICON_CHARGING[${dict["percentage"]} / 10]}
			else
				dict["class"]="discharging"
				dict["icon"]=${ICON[${dict["percentage"]} / 10]}
			fi
			;;
		"time to full" | "time to empty")
			dict["time_to"]="Time to $(echo "$key" | awk '{print tolower($0)}'): $value"
			;;
		esac
	done <<<"$(upower -i "$BATTERY")"

	# Print the associative array in JSON-like format
	echo -n "{"
	for key in "${!dict[@]}"; do
		echo -n "\"$key\": \"${dict[$key]}\","
	done | sed '$s/,$//'
	echo "}"
}

update_eww() {
	eww update "battery=$(declare -p dict)"
}

upower -m | while read -r _; do
	# update_eww "$(main)"
	main
	#done <<< "$(upower -m)"
done
