#!/bin/bash

current_hour=$(date +%H)
greeting=""

if [ $current_hour -ge 5 ] && [ $current_hour -lt 12 ]; then
    greeting="morning"
elif [ $current_hour -ge 12 ] && [ $current_hour -lt 18 ]; then
    greeting="afternoon"
else
    greeting="evening"
fi

echo "$greeting"
