#!/usr/bin/bash

param="$1"

if [[ $param == "--down" ]]; then
    hyprctl dispatch workspace +1

elif [[ $param == "--up" ]]; then
    hyprctl dispatch workspace -1

elif [[ $param == "--set" ]]; then
    hyprctl dispatch workspace $2

elif [[ $param == "--setnode" ]]; then
    hyprctl dispatch focuswindow pid:"$2"

elif [[ $param == "--close" ]]; then
    hyprctl dispatch closewindow pid:"$2"
fi