#!/usr/bin/bash

dir="/home/tokyob0t/.config/eww/scripts"


pkill eww
killall eww

eww daemon
eww open topbar
eww open wallpaper

## This now is managed by the notifCatch script

bash $dir/airplanemode --get > /dev/null 2>&1 &
# bash $dir/bspwm_hideTopbar  > /dev/null 2>&1 &
