#!/usr/bin/bash

dir="/home/tokyob0t/.config/eww/scripts"

zsh $dir/notifCatch &

pkill eww
killall eww

eww daemon
eww open topbar

eww open wallpaper

sleep 2

notify-send "Startup Notification" "Welcome $(whoami)" &

zsh $dir/airplaneMode --get &
