#!/usr/bin/bash


dir="/home/$(whoami)/.config/eww/scripts"


if [[ $1 == "--get" ]]; then
    pactl get-source-volume @DEFAULT_SOURCE@ | grep -Po '[0-9]{1,3}(?=%)' | head -1

elif [[ $1 == "--getState" ]]; then
    pactl get-source-mute @DEFAULT_SOURCE@ | awk '{print $2}'
    
elif [[ $1 == "--set" ]]; then
    pactl set-source-volume @DEFAULT_SOURCE@ $2%
    
elif [[ $1 == "--up" ]]; then
    pactl set-source-volume @DEFAULT_SOURCE@ +10%

elif [[ $1 == "--down" ]]; then
    pactl set-source-volume @DEFAULT_SOURCE@ -10%
    
elif [[ $1 == "--toggle" ]]; then
    mute=$(pactl get-source-mute @DEFAULT_SOURCE@ | awk '{print $2}')
    
    if [[ $mute == "yes" ]]; then
        pactl set-source-mute @DEFAULT_SOURCE@ toggle
        current_volume=$(pactl get-source-volume @DEFAULT_SOURCE@ | grep -Po '[0-9]{1,3}(?=%)' | head -1)
        volume_icon=""
        volume_level=$current_volume
    else
        pactl set-source-mute @DEFAULT_SOURCE@ toggle
        volume_icon=""
        volume_level=--
    fi
    zsh "$dir/osd" "$volume_icon" "$volume_level"
fi
