#!/usr/bin/zsh


# This script is only for catching notifications

notifDuration=$(eww get notifDuration)


tiramisu -s -o '{"id": "#id","source": "#source", "title": "#summary", "content": "#body", "timeout": "#timeout"}' | while read -r line; do

    notifMuted=$(eww get notifMuted)

    # Get the current time for every notification
    current_time=$(date "+%I:%M %p")
    

    # Add the current time
    line=$(echo "$line" | jq --arg current_time "$current_time" '. + {"time": $current_time}')

    if [[ $notifMuted == false ]]; then
        eww open notifpopup
        python /home/$(whoami)/.config/eww/scripts/notifManage --send "$line"
        eww update notifNow="$line"
        eww update notifNowRevealer=true
        echo "$line"
        
        sleep $notifDuration
        eww update notifNowRevealer=false
        eww close notifpopup
    else
        python /home/$(whoami)/.config/eww/scripts/notifManage --send "$line"
    fi
done
