#!/usr/bin/bash

choice=$1
var=$2
state=$(eww get $var)

toggleVar(){

if [[ $state == false ]]; then
    eww update $var=true
elif [[ $state == true ]]; then
    eww update $var=false
fi
}


if [[ $choice == "--toggle" ]]; then
    toggleVar
fi