#!/usr/bin/bash

var=$1
window=$2

stateWindow=$(eww list-windows | grep $window | awk '{print substr ($0, 0, 1)}')

if [[ $stateWindow != '*' ]]; then
    eww open $window
    eww update $var=true

elif [[ $stateWindow == '*' ]]; then
    eww update $var=false
    sleep 0.25
    eww close $window
fi

