#!/bin/bash

new_volume="$1"

if [ "$new_volume" -lt 0 ]; then
    new_volume=0
elif [ "$new_volume" -gt 100 ]; then
    new_volume=100
fi

# Redondear el nuevo volumen al múltiplo de 2 más cercano
new_volume=$((new_volume / 3 * 3))

pactl set-sink-volume @DEFAULT_SINK@ "$new_volume%"

echo "Volumen ajustado: $new_volume%"
