#!/bin/bash

dir="/home/$(whoami)/.config/eww/scripts"

icon() {
    local value="$1"
    local value2="$2"

    if [[ $value2 == "no" ]]; then
        if ((value < 30)); then
            # echo ""
            echo $low
        elif ((value < 65)); then
            # echo ""
            echo $mid
        else
            # echo ""
            echo $high
        fi
    else
        # echo "󰝟"
        echo $muted
    fi
}



if [[ $1  == "--get" ]]; then

    low=$($dir/python/gtk_icon.py audio-volume-low-symbolic)
    mid=$($dir/python/gtk_icon.py audio-volume-medium-symbolic)
    high=$($dir/python/gtk_icon.py audio-volume-high-symbolic)
    muted=$($dir/python/gtk_icon.py audio-volume-muted-symbolic)

    vol=$(pactl get-sink-volume @DEFAULT_SINK@ | grep -Po '[0-9]{1,3}(?=%)' | head -1)
    muted_state=$(pactl get-sink-mute @DEFAULT_SINK@ | awk '{print $2}')
    icon=$(icon "$vol" "$muted_state")


    echo "{\"icon\": \"$icon\", \"value\": \"$vol\"}"

    pactl subscribe | grep --line-buffered "on sink" | while read -r _ ; do
            vol=$(pactl get-sink-volume @DEFAULT_SINK@ | grep -Po '[0-9]{1,3}(?=%)' | head -1)
            muted_state=$(pactl get-sink-mute @DEFAULT_SINK@ | awk '{print $2}')
            icon=$(icon "$vol" "$muted_state")
            echo "{\"icon\": \"$icon\", \"value\": \"$vol\"}"
            zsh "$dir/osd" "$icon" "$vol" "int" > /dev/null 2>&1 &
    done

elif [[ $1 == "--set" ]]; then
    
    if (( $2 >= 0 && $2 <= 100 )); then
        pactl set-sink-volume @DEFAULT_SINK@ $2%
    fi
    
elif [[ $1 == "--up" ]]; then

    new_volume=$((vol + 5))
    
    if (( new_volume <= 100 )); then
        pactl set-sink-volume @DEFAULT_SINK@ +5%
    fi

elif [[ $1 == "--down" ]]; then
    pactl set-sink-volume @DEFAULT_SINK@ -5%
    
elif [[ $1 == "--toggle" ]]; then
    pactl set-sink-mute @DEFAULT_SINK@ toggle
fi
