#!/bin/bash

dir="/home/$(whoami)/.config/eww/scripts"

icon() {
    local value="$1"
    local muted="$2"

    if [[ $muted == "yes" || $value == 0 ]]; then
        echo "󰝟"

    elif ((value < 30)); then
        echo ""
    elif ((value < 70)); then
        echo ""
    else
        echo ""
    fi
}

pactl subscribe | grep --line-buffered "on sink" | while read -r _ ; do

        vol=$(pactl get-sink-volume @DEFAULT_SINK@ | grep -Po '[0-9]{1,3}(?=%)' | head -1)
        muted=$(pactl get-sink-mute @DEFAULT_SINK@ | awk '{print $2}')
        icon=$(icon "$vol" "$muted")

        echo "{\"value\": \"$vol\", \"muted\": \"$muted\"}"

done
