#!/usr/bin/bash

dir="/home/$(whoami)/.config/eww/scripts"

if [[ $1 == "--get" ]]; then
    pactl get-sink-volume @DEFAULT_SINK@ | grep -Po '[0-9]{1,3}(?=%)' | head -1

elif [[ $1 == "--getState" ]]; then
    pactl get-sink-mute @DEFAULT_SINK@ | awk '{print $2}'

elif [[ $1 == "--set" ]]; then

    if (( $2 >= 0 && $2 <= 100 )); then
        pactl set-sink-volume @DEFAULT_SINK@ $2%
    fi
    
elif [[ $1 == "--up" ]]; then
    current_volume=$(pactl get-sink-volume @DEFAULT_SINK@ | grep -Po '[0-9]{1,3}(?=%)' | head -1)
    new_volume=$((current_volume + 5))

    if (( new_volume <= 100 )); then
        pactl set-sink-volume @DEFAULT_SINK@ ${new_volume}%
        zsh $dir/osd "" $new_volume
    
    fi
    
elif [[ $1 == "--down" ]]; then
    pactl set-sink-volume @DEFAULT_SINK@ -5%
    zsh $dir/osd "" $(pactl get-sink-volume @DEFAULT_SINK@ | grep -Po '[0-9]{1,3}(?=%)' | head -1)
    
elif [[ $1 == "--toggle" ]]; then
    pactl set-sink-mute @DEFAULT_SINK@ toggle
fi
