#!/usr/bin/bash
param="$1"

current=$(eww get workspaces)

if [[ $param == "--down" ]]; then
    if [[ $((current+1)) -gt 9 ]]; then
        wmctrl -s 0
    else
        wmctrl -s $((current+1))
    fi
elif [[ $param == "--up" ]]; then
    if [[ $((current-1)) -lt 0 ]]; then
        wmctrl -s 9
    else
        wmctrl -s $((current-1))
    fi
elif [[ $param == "--set" ]]; then
    wmctrl -s $2
fi

