general {
    lock_cmd = astal-lua request -i luar lock       # avoid starting multiple hyprlock instances.
    before_sleep_cmd = astal-lua request -i luar lock    # lock before suspend.
    after_sleep_cmd = hyprctl dispatch dpms on  # to avoid having to press a key twice to turn on the display.
}

listener {
    timeout = 150
    on-timeout = brightnessctl -s -e4 -n2 set 10%
    on-resume = brightnessctl -r
}

# turn off keyboard backlight, comment out this section if you dont have a keyboard backlight.
listener { 
    timeout = 150                                          # 2.5min.
    on-timeout = brightnessctl -sd asus::kbd_backlight set 0 # turn off keyboard backlight.
    on-resume = brightnessctl -rd asus::kbd_backlight        # turn on keyboard backlight.
}

listener {
    timeout = 300                                 # 5min
    on-timeout = astal-lua request -i luar lock
}

listener {
    timeout = 330                                                     # 5.5min
    on-timeout = hyprctl dispatch dpms off                            # screen off when timeout has passed
    on-resume = hyprctl dispatch dpms on && brightnessctl -r          # screen on when activity is detected after timeout has fired.
}

listener {
    timeout = 1800                                # 30min
    on-timeout = systemctl suspend                # suspend pc
}
