###################
### KEYBINDINGS ###
###################

# See https://wiki.hyprland.org/Configuring/Keywords/
$mainMod = SUPER # Sets "Windows" key as main modifier


# Set programs that you use
$terminal = ghostty
# $terminalAlt = blackbox
$fileManager = nautilus --new-window 
# $webBrowser = XDG_CURRENT_DESKTOP=GNOME firefox
$webBrowser = firefox
# $launcher = lua-shell toggle-window launcher
$launcher = astal-lua request -i luar -t launcher
$screenshotSelection = astal-lua request -i luar screenshot
$screenshotScreen = astal-lua request -i luar screenshot-full
$overview = astal-lua request -i luar -t overview
$lockScreen = astal-lua request -i luar lock
$clipboard = astal-lua request -i luar -t clipboard

gesture = 4, horizontal, workspace

# Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more
bind = $mainMod SHIFT, Q, exit,
bind = $mainMod SHIFT, C, togglefloating,
bind = $mainMod, W, killactive,
bind = $mainMod, T, exec, $terminal
# bind = $mainMod SHIFT, T, exec, $terminalAlt
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, F, exec, $webBrowser
bind = $mainMod, R, exec, $launcher
bind = $mainMod, L, exec, $lockScreen
bind = $mainMod, V, exec, $clipboard
bind = $mainMod, TAB, exec, $overview 
bind = $mainMod SHIFT, S, exec, $screenshotSelection
bind = $mainMod SHIFT, A, exec, $screenshotScreen 


# Move focus with mainMod + arrow keys
bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d

# Switch workspaces with mainMod + [0-9]
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9
bind = $mainMod SHIFT, 0, movetoworkspace, 10

# Example special workspace (scratchpad)
# bind = $mainMod, S, togglespecialworkspace, magic
# bind = $mainMod SHIFT, S, movetoworkspace, special:magic
bind = $mainMod SHIFT, p, pin 

binde = ALT, Tab, cyclenext
binde = ALT SHIFT, Tab, cyclenext, prev
binde = ALT, Tab, bringactivetotop
binde = ALT SHIFT, Tab, bringactivetotop

bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

bindel = ,XF86AudioRaiseVolume, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+
bindel = ,XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindel = ,XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindel = ,XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
bindel = ,XF86MonBrightnessUp, exec, brightnessctl -e4 -n2 set 5%+
bindel = ,XF86MonBrightnessDown, exec, brightnessctl -e4 -n2 set 5%-
