##############################
### WINDOWS AND WORKSPACES ###
##############################

windowrule = noblur,class:Xdg-desktop-portal-gtk
windowrule = bordersize 0,class:Xdg-desktop-portal-gtk
windowrule = decorate,class:Xdg-desktop-portal-gtk
windowrule = noshadow,class:Xdg-desktop-portal-gtk
windowrule = float,class:xdg-desktop-portal-gtk

windowrule = opacity 0.0 override, class:^(xwaylandvideobridge)$
windowrule = noanim, class:^(xwaylandvideobridge)$
windowrule = noinitialfocus, class:^(xwaylandvideobridge)$
windowrule = maxsize 1 1, class:^(xwaylandvideobridge)$
windowrule = noblur, class:^(xwaylandvideobridge)$
windowrule = nofocus, class:^(xwaylandvideobridge)$

windowrule = float, pin, opaque, title:(?i)^(Picture-in-picture)(.*)

windowrule = suppressevent maximize, class:.*
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0
windowrule = immediate, class:^(cs2)$
windowrule = immediate, class:(steam_app)(.*)
# windowrule = bordersize 0,floating:1

windowrule = float,xwayland:1
windowrule = float,class:re.sonny.Commit

windowrule = renderunfocused,initialClass:discord
windowrule = float,initialClass:firefox,title:.*(Bitwarden).*
windowrule = noscreenshare,initialClass:firefox,title:^WhatsApp.*
windowrule = noscreenshare,initialClass:discord,title:.*discol.*

layerrule = animation slide right, astal-qsettings
layerrule = animation slide top, astal-notifpopup
layerrule = animation slide top, astal-overview
layerrule = animation slide top, astal-launcher
layerrule = animation slide bottom, astal-dock
layerrule = noanim, astal-screenshot
